### ISSUE TITLE
attempt to index field 'image' (a nil value)

### ISSUE THREAD

**Issue by ProGamerGov** [VaKonS/neural-style#3]
While testing out the latest version of your modified Neural-Style, I am getting the following error:

```
Scale: 1-1, simple scaling.
/home/ubuntu/torch/install/bin/luajit: /home/ubuntu/torch/install/share/lua/5.1/image/init.lua:663: attempt to index field 'image' (a nil value)
stack traceback:
        /home/ubuntu/torch/install/share/lua/5.1/image/init.lua:663: in function 'scale'
        neural_style_v.lua:530: in function 'main'
        neural_style_v.lua:838: in main chunk
        [C]: in function 'dofile'
        ...untu/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x00405d50

```

Edit: 

The issue started appearing in this commit: https://github.com/VaKonS/neural-style/commit/bc4ae153e3490c1147ddb6402003fd215924a197

**Comment by VaKonS** [comment]
@ProGamerGov, please try the fix ([current commit](https://github.com/VaKonS/neural-style/tree/f4f1c689a25a7559020714e858a220ae61ae93bd)), will it help?

**Comment by ProGamerGov** [comment]
@VaKonS 

I just tried the current version and it resulted in 0 loss: 

```
  Total loss: 0.000000
Iteration 100 / 1500
  Total loss: 0.000000
Iteration 150 / 1500
  Total loss: 0.000000
Iteration 200 / 1500
  Total loss: 0.000000
Iteration 250 / 1500
  Total loss: 0.000000
Iteration 300 / 1500
  Total loss: 0.000000
Iteration 350 / 1500
  Total loss: 0.000000

```

Edit: This could be an issue with the multi-gpu parameter.

**Comment by ProGamerGov** [comment]
This issue appears to have been resolved in the latest version.

**Comment by VaKonS** [comment]
@ProGamerGov, I'm just curious, did you find out why this error was appearing? (Because I didn't understand that). 
p.s. Merry Christmas (if you celebrate it), by the way, and Happy New Year! :)

**Comment by VaKonS** [comment]
I mean, second error, absent losses.

**Comment by ProGamerGov** [comment]
@VaKonS I'm not entirely sure what was causing this error. If it wasn't something you fixed, then I imagine it could have been caused by one or parameters.

**Comment by ProGamerGov** [comment]
@VaKonS 

Comparing https://github.com/VaKonS/neural-style/commit/bc4ae153e3490c1147ddb6402003fd215924a197 to the latest version using a diff checking tool, I can see exactly what changed.

Latest version: https://github.com/VaKonS/neural-style/blob/2ef9342c369b4a3a7ce985d1ef7c0746d9dbfe5a/neural_style.lua#L531-L542


First appearance of the issue: https://github.com/VaKonS/neural-style/blob/bc4ae153e3490c1147ddb6402003fd215924a197/neural_style.lua#L521-L531


There was new code introduced between these lines on the version with the issue: 


Version with issue: https://github.com/VaKonS/neural-style/blob/bc4ae153e3490c1147ddb6402003fd215924a197/neural_style.lua#L471-L472


The latest version: https://github.com/VaKonS/neural-style/blob/2ef9342c369b4a3a7ce985d1ef7c0746d9dbfe5a/neural_style.lua#L475-L481

---

The issue must have been related to the code changes I listed above, as I doubt the addition of the fragment counter had anything to do with the issue being resolved.

**Comment by VaKonS** [comment]
@ProGamerGov, the problem with "nil value" was because `image.scale` can not process images in GPU format ("torch.CudaTensor"), it only accepts doubles, floats or integers ("torch.DoubleTensor" etc.).

So I converted image from CUDA/OpenCL format to double precision values during scaling in [line 530](https://github.com/VaKonS/neural-style/blob/e4291e50a05f171729f0b25013a1b52e0a671fb9/neural_style.lua#L530):
[`img = image.scale(img, W, H, 'bilinear')`](https://github.com/VaKonS/neural-style/blob/e4291e50a05f171729f0b25013a1b52e0a671fb9/neural_style.lua#L530)
 v v v
[` img = image.scale(img:double(), W, H, 'bilinear')`](https://github.com/VaKonS/neural-style/blob/f4f1c689a25a7559020714e858a220ae61ae93bd/neural_style.lua#L529)

And after scaling turned image back to GPU format at [line 537](https://github.com/VaKonS/neural-style/blob/f4f1c689a25a7559020714e858a220ae61ae93bd/neural_style.lua#L537):
[`img = img:type(dtype)`](https://github.com/VaKonS/neural-style/blob/f4f1c689a25a7559020714e858a220ae61ae93bd/neural_style.lua#L537)

That fixed the issue with "absent image field".

But I didn't understand why the losses were zero (and therefore didn't try to fix it).
