### ISSUE TITLE
Example please

### ISSUE THREAD

**Issue by damirkotoric** [VaKonS/neural-style#6]
Hi, can you give some more context about what the default values are for your new options (-overlap_times, -scale_down, -scale_up, -scale_steps, -expand_small)

I want to generate a 5000x5000 image. What would be the command I should write?

Many thanks for your code!

**Comment by ProGamerGov** [comment]
The size of your input content image will be the size of the output image. The `-image_size` parameter controls the size of each tile.

**Comment by damirkotoric** [comment]
Okay, so let me just clarify I understand right:

Say I want to generate a 5000x5000 pixel image and my machine can only reliably generate a 500px image tile. I would then run:

`th neural_style.lua -style_image img/style.jpg -content_image img/input_5000x5000.jpg -image_size 500`

This would then generate a 5000x5000 pixel image with 10 tiles of 500x500 pixels each. Correct?

**Comment by ProGamerGov** [comment]
The number of tiles that are used, is automatically calculated. But you will need more than five 500px tiles (because of the overlap), to cover one row.

**Comment by ProGamerGov** [comment]
The `-save_iter` parameter is broken, and only works with `-save_iter 1`. But using `-save_iter 1` doesn't save every iteration, and instead saves after a row has been completed. The "-init_image" parameter also doesn't work, but the "-content_image" parameter can be substituted in it's place. 

---
---

Below are some examples produced with `-save_iter 1`:


**Individual Step Animations:** 

Step 1 Animation: https://gfycat.com/FrigidGleamingHorsemouse

Step 2 Animation: https://gfycat.com/AromaticAgedArizonaalligatorlizard

Step 3 Animation: https://gfycat.com/SpotlessPersonalDassie

---

Steps 1-2: https://gfycat.com/EagerEveryAfricanwildcat

Steps 1-3: https://gfycat.com/ArtisticAdorableGoose

---

**Comment by VaKonS** [comment]
@damirkotoric, hi, the default values are given in lines [52-56](https://github.com/VaKonS/neural-style/blob/c7ece9b8cd93b7aa7adf86a26663736e55a28ffa/neural_style.lua#L52-L56).

**1)** The content image will be scaled from ( _content_size * scale_down_ ) to ( _content_size * scale_up_ ).
By ( _scale_steps_ ) passes.

For example, you have 5000x5000 content image.
The command
"th neural_style.lua -scale_down **_0.5_** -scale_up **_2_** ..."
will process 3 resolutions:
2500x2500
5000x5000
10000x10000 = this will be the final output size.

Or you can use **_negative_** values to specify exact image size (as was suggested by @ProGamerGov).
"th neural_style.lua -scale_down **_-500_** -scale_up **_-7500_** ..."
will process 5 resolutions: 500x500, 984x984, 1936x1936, 3811x3811, 7500x7500.

As @ProGamerGov correctly noted, the default scale is "from 1 to 1", and output image _by default_ will be equal to content size.

**2)** The number of upscale steps is set by "-scale_steps" parameter.
By default steps are "auto" - each step will upscale image by 2 or less.

**3)** Option "-expand_small" should slightly affect images with scale less than "image_size".
The effect depends on content / style size and on model.
Try it with "-scale_down **_-100_** **_-save_iter 1_**" and you'll probably notice some difference.

**4)** And yes, since tiles are processed by "group of iterations" at once, this implementation can not save every iteration.
The "-save_iter" option can be set to:
0 - save only final image;
1 - save every row of processed tiles.

p.s. I didn't change much, whole processing is still @jcjohnson's. :)

**Comment by VaKonS** [comment]
@damirkotoric, the "-overlap_times" option (default is 2 - shift tiles by 1/2 of their width) should help when tiles are too noticeable.
Tile edges will be smoother with large values, but note that processing will be _nearly_ (overlap_times * overlap_times) longer.

**Comment by rahidz** [comment]
Does it process the smaller resolution outputs to generate the larger ones, or does it do each resolution separately?

Or in other words, is there any advantage to doing

` th neural_style.lua -scale_down 0.5 -scale_up 2 ...`

vs.

` th neural_style.lua -scale_up 2 ...`  ?

**Comment by VaKonS** [comment]
Hi, @rahidz, sorry for not responding (some unwanted things happened, I don't have a PC at the moment, to say the least). 🙃
Yes, it processes the results of previous pass. I suppose, you've already figured that out by yourself, again, sorry for being irresponsive.
